name: teriak
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  internet_connection_checker_plus: ^2.7.2
  get: ^4.7.2
  google_fonts: ^6.2.1
  barcode_widget: ^2.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0





flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_assets:
assets_path: assets/images/
output_path: lib/core/themes
filename: assets. dart    


