name: teriak
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.4.0
  internet_connection_checker_plus: ^2.7.2
  shared_preferences: ^2.5.3
  sizer: ^2.0.15
  geolocator: ^14.0.1
  latlong2: ^0.9.0
  flutter_map: ^6.1.0
  nominatim_geocoding: ^0.0.6
  mobile_scanner: ^7.0.1
  barcode_widget: ^2.0.1
  

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_assets: 
  assets_path: assets/images/
  output_path: lib/core/themes
  filename: app_assets.dart
